import {Dimensions} from 'react-native';
const DEVICE_WIDTH = Dimensions.get('window').width;
const DEVICE_HEIGHT = Dimensions.get('window').height;

export default {
  container: {
    flex: 1,
    position: 'relative',
  },
  tes: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    zIndex: 5,
  },
  imgArrow: {
    width: 20,
    height: 20,
  },
  body: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    position: 'absolute',
    top: 0,
    left: 0,
    width: DEVICE_WIDTH,
    height: DEVICE_HEIGHT + 200,
    alignItems: 'center',
    padding: 12,
  },
  backgroundContent: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    backgroundColor: 'green',
    height: 230,
    width: DEVICE_WIDTH,
    position: 'absolute',
    bottom: 0,
    left: 0,
  },
  contentBack: {
    flexDirection: 'row',
    marginHorizontal: 28,
    marginVertical: 10,
  },
  imageArrow: {
    elevation: 10,
    top: 3,
  },
  viewBack: {
    flexDirection: 'row',
    top: 5,
    marginHorizontal: 10,
  },
  fontText: {
    fontSize: 20,
    color: 'white',
  },
  titleMin: {
    marginLeft: 10,
    fontSize: 16,
    color: 'white',
    backgroundColor: '#084518',
    borderRadius: 20,
    padding: 5,
    width: 80,
    textAlign: 'center',
  },
  content: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    backgroundColor: '#fff',
    height: 170,
    width: DEVICE_WIDTH,
    position: 'absolute',
    bottom: 0,
    left: 0,
  },
  contentMenu: {
    marginLeft: 15,
    padding: 10,
    paddingTop: 20,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  firstContent: {
    flexDirection: 'column',
    flex: 1,
    justifyContent: 'space-between',
  },
  fontSize: {
    marginBottom: 8,
    fontSize: 20,
    color: '#000d',
    fontWeight: 'bold',
  },
  flexRow: {
    flexDirection: 'row',
  },
  textGray: {
    fontSize: 16,
    marginTop: 5,
    color: 'gray',
  },
  viewTrophy: {
    flexDirection: 'row',
    marginHorizontal: 12,
    backgroundColor: 'white',
    borderRadius: 20,
    width: 130,
    elevation: 10,
    padding: 5,
    textAlign: 'center',
  },
  titleTrophy: {
    fontSize: 16,
    color: 'black',
    marginLeft: 5,
  },
  imgGojek: {
    width: 50,
    height: 50,
    padding: 1,
    borderRadius: 18,
    right: 20,
  },
  viewButton: {
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'space-between',
    marginHorizontal: 25,
    marginVertical: 15,
  },
  buttonPickup: {
    textAlign: 'center',
    borderRadius: 20,
    backgroundColor: 'green',
    color: '#fff',
    fontSize: 18,
    padding: 10,
    width: 260,
  },
};
